apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - middlewares-global.yaml
  - middlewares-admin-auth.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hosting-platform
      app.kubernetes.io/component: traefik
