apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: dex-config
    files:
      - config.yaml

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/part-of: hosting-platform
      app.kubernetes.io/component: identity-provider
