apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hosting-platform-stable
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/phoenixtechnam/k8s-hosting-platform
  ref:
    branch: stable
  # For private repos, uncomment and create the secret:
  # secretRef:
  #   name: flux-github-auth
