apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roundcube-data
  namespace: mail
  labels:
    app: roundcube
    app.kubernetes.io/part-of: hosting-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      # 1Gi for sqlite DB + sessions + identities + uploaded attachments cache.
      # The actual mail storage lives in Stalwart, not here.
      storage: 1Gi
