apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/phoenixtechnam/hosting-platform/backend
    newTag: "latest"
  - name: ghcr.io/phoenixtechnam/hosting-platform/admin-panel
    newTag: "latest"
  - name: ghcr.io/phoenixtechnam/hosting-platform/client-panel
    newTag: "latest"
