apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: platform
data:
  environment: "production"
  log-level: "warn"
  default-storage-class: "longhorn"
  ingress-base-domain: "${DOMAIN}"
  cluster-issuer-name: "letsencrypt-prod-http01"
  admin-url: "https://admin.${DOMAIN}"
  client-url: "https://client.${DOMAIN}"
  cors-origins: "https://admin.${DOMAIN},https://client.${DOMAIN}"
