/**
 * F4 — Renders an ordered list of enabled WAF rule exclusions into the
 * ModSecurity .conf body that gets mounted into the modsec-crs pod.
 *
 * Pure function — no DB, no K8s, no I/O. Unit-tested in renderer.test.ts.
 *
 * Rendered file lives at:
 *   /etc/modsecurity.d/owasp-crs/rules/REQUEST-901-EXCLUSION-RULES-BEFORE-CRS-DYNAMIC.conf
 *
 * The "-BEFORE-CRS" suffix matches CRS's auto-load convention; the 901
 * sort key puts it AFTER the static 900 file (so the static file's
 * exclusions still apply first) but still BEFORE the main CRS rules so
 * the ctl: actions take effect.
 *
 * Rule ID range: 9001000-9001999 reserved for this renderer. Each row
 * occupies exactly one rule ID (sequential by row order). Static file
 * uses 9000xxx, so there's no collision risk.
 *
 * Matching mechanism: every emitted SecRule fires on
 *   REQUEST_HEADERS:X-Forwarded-Host @rx <hostnameRegex>
 * Reason: Traefik's modsecurity plugin proxies inspected requests with
 * Host=modsec-crs.traefik.svc.cluster.local — matching REQUEST_HEADERS:Host
 * never fires. See scripts/ci-modsec-exclusion-check.sh which enforces
 * this invariant on the generated conf string as well as on YAML.
 */

import type { WafRuleExclusion } from '@k8s-hosting/api-contracts';

export const DYNAMIC_RULE_ID_BASE = 9_001_000;
export const DYNAMIC_RULE_ID_MAX = 9_001_999;

const HEADER = `# AUTO-GENERATED by waf-rule-exclusions reconciler.
# Do NOT edit by hand — your changes will be overwritten.
# Source of truth: waf_rule_exclusions table.
# Companion to the static REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
# from k8s/base/modsecurity-crs/exclusion-rules-configmap.yaml.
`;

const EMPTY_BODY = `${HEADER}
# No DB-rendered exclusions are currently enabled.
# Operators can add exclusions from the WAF Events tab in the
# admin panel (/settings/security-hardening).
`;

export interface RenderResult {
  readonly body: string;
  readonly count: number;
  /** Sha256 (hex) of `body` — used to detect changes and bump the
   * modsec-crs Deployment annotation. */
  readonly hash: string;
}

/**
 * Render the SecRule snippet for one exclusion.
 * Caller is responsible for ensuring rowIndex < (DYNAMIC_RULE_ID_MAX - DYNAMIC_RULE_ID_BASE).
 */
export const renderOneExclusion = (
  exclusion: Pick<WafRuleExclusion, 'ruleId' | 'hostnameRegex' | 'scope' | 'reason' | 'createdBy'>,
  rowIndex: number,
): string => {
  // Defense-in-depth: if `"` reaches the renderer despite the Zod +
  // DB CHECK guards, refuse rather than emit a broken SecRule that
  // would let the rest of the line escape the @rx string and crash
  // modsec-crs (or worse, become an attacker-controlled SecRule body).
  // Trailing backslash is blocked by the DB CHECK + Zod regexParseable.
  if (exclusion.hostnameRegex.includes('"')) {
    throw new Error(
      `waf-rule-exclusions renderer: unsafe hostnameRegex characters in row ${exclusion.ruleId} — refusing to render`,
    );
  }
  // Belt-and-braces against a row that somehow has a trailing backslash
  // (bypassing every other layer). The PCRE parser crash this prevents
  // is the cluster-wide WAF DoS the security review called out.
  if (exclusion.hostnameRegex.endsWith('\\')) {
    throw new Error(
      `waf-rule-exclusions renderer: trailing backslash in row ${exclusion.ruleId} — refusing to render (would crash modsec-crs)`,
    );
  }
  const ruleId = DYNAMIC_RULE_ID_BASE + rowIndex;
  const ctl =
    exclusion.scope === 'full_disable'
      ? `ctl:ruleRemoveById=${exclusion.ruleId}`
      : `ctl:ruleRemoveTargetById=${exclusion.ruleId};ARGS_NAMES`;

  // Multi-line comment header so operators can grep the .conf for the reason.
  // Strip any CR/LF from reason just in case (DB CHECK constraint blocks newlines,
  // but defensive belt-and-braces here).
  const safeReason = exclusion.reason.replace(/[\r\n]+/g, ' ').slice(0, 256);
  const safeCreatedBy = exclusion.createdBy.replace(/[\r\n"]+/g, '_').slice(0, 64);

  // Trailing `\\` after each line is the CRS/ModSecurity continuation marker.
  // The final line has NO trailing `\\` so the SecRule terminates.
  return [
    `# rule ${exclusion.ruleId} for ${exclusion.hostnameRegex} — ${safeReason} (by ${safeCreatedBy})`,
    `SecRule REQUEST_HEADERS:X-Forwarded-Host "@rx ${exclusion.hostnameRegex}" \\`,
    `    "id:${ruleId},\\`,
    `     phase:1,\\`,
    `     pass,\\`,
    `     nolog,\\`,
    `     ${ctl}"`,
  ].join('\n');
};

/**
 * Render all enabled exclusions into one .conf body + sha256 hash.
 *
 * Input MUST already be sorted by createdAt ASC (or any stable order) so
 * the hash is deterministic across reconciler ticks. The service layer
 * sort key is (createdAt ASC, id ASC).
 *
 * If more than (DYNAMIC_RULE_ID_MAX - DYNAMIC_RULE_ID_BASE + 1) rows
 * are passed in, throws — caller must enforce the cap at the service
 * layer (currently 1000 enabled rows).
 */
export const renderExclusions = (enabledExclusions: ReadonlyArray<WafRuleExclusion>): RenderResult => {
  const max = DYNAMIC_RULE_ID_MAX - DYNAMIC_RULE_ID_BASE + 1;
  if (enabledExclusions.length > max) {
    throw new Error(
      `waf-rule-exclusions renderer: ${enabledExclusions.length} exclusions exceeds reserved rule-ID range (${max})`,
    );
  }

  if (enabledExclusions.length === 0) {
    return {
      body: EMPTY_BODY,
      count: 0,
      hash: sha256Hex(EMPTY_BODY),
    };
  }

  const parts = [HEADER, ''];
  for (let i = 0; i < enabledExclusions.length; i += 1) {
    parts.push(renderOneExclusion(enabledExclusions[i]!, i));
    parts.push('');
  }
  const body = parts.join('\n');
  return {
    body,
    count: enabledExclusions.length,
    hash: sha256Hex(body),
  };
};

// Local sha256 — module-scoped so renderer.ts has zero non-test imports
// other than the contracts type (which is types-only and tree-shakes
// to nothing in JS).
import { createHash } from 'node:crypto';

const sha256Hex = (input: string): string => createHash('sha256').update(input).digest('hex');
