apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - rbac.yaml
  - network-policies.yaml
  - resource-quotas.yaml
  - platform-config.yaml
  - cluster-issuers.yaml
  - database.yaml
  - redis.yaml
  - backend-deployment.yaml
  - admin-deployment.yaml
  - client-deployment.yaml
  - ingress.yaml
  - sftp-gateway.yaml
  - sftp-gateway-netpol.yaml
  - oauth2-proxy/
  - update-checker-rbac.yaml
  - update-checker-cronjob.yaml
