apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/part-of: hosting-platform
    purpose: management
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: hosting-platform
    purpose: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: hosting
  labels:
    app.kubernetes.io/part-of: hosting-platform
    purpose: client-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    app.kubernetes.io/part-of: hosting-platform
    purpose: platform-services
