apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: platform
data:
  environment: "development"
  log-level: "debug"
  default-storage-class: "local-path"
  ingress-base-domain: "k8s-platform.test"
  cluster-issuer-name: "selfsigned-issuer"
  admin-url: "http://admin.k8s-platform.test"
  client-url: "http://client.k8s-platform.test"
  cors-origins: "http://admin.k8s-platform.test,http://client.k8s-platform.test,http://localhost:5173,http://localhost:5174"
